set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
create_clock -name FCLK -period 10.000 [get_pins {_PS7/FCLKCLK[0]}]
set_property PACKAGE_PIN U5 [get_ports {refclk[0]}]
set_property PACKAGE_PIN V5 [get_ports {refclk[1]}]
set_property IOSTANDARD BLVDS_25 [get_ports {auxn}]
set_property PACKAGE_PIN AB19 [get_ports {auxn}]
set_property IOSTANDARD BLVDS_25 [get_ports {auxp}]
set_property PACKAGE_PIN AB18 [get_ports {auxp}]
set_property PACKAGE_PIN AA3 [get_ports {tx[0]}]
set_property PACKAGE_PIN AB3 [get_ports {tx[1]}]
set_property PACKAGE_PIN W2 [get_ports {tx[2]}]
set_property PACKAGE_PIN Y2 [get_ports {tx[3]}]
